# Generated by Django 5.0.7 on 2024-07-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, unique=True)),
                ('blog_summary', models.TextField()),
                ('blog_context', models.TextField()),
                ('blog_category', models.TextField()),
                ('blog_is_active', models.BooleanField(default=True)),
                ('blog_isGenByAi', models.BooleanField(default=False)),
                ('blog_keywords', models.JSONField(blank=True, default=list)),
                ('blog_created', models.DateTimeField(auto_now_add=True)),
                ('blog_updated', models.DateTimeField(auto_now=True)),
                ('blog_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogModel', to='User.blogger')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
