# Generated by Django 5.0.7 on 2024-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_blog_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
