# Generated by Django 5.0.6 on 2024-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRunning', models.BooleanField(default=False)),
                ('CheckFrequency', models.IntegerField(default=1)),
                ('CheckToDate', models.IntegerField(default=90)),
            ],
        ),
    ]
