# Generated by Django 5.0.6 on 2024-07-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot_Settings',
            new_name='Bot_Setting',
        ),
    ]
